apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/jyotshinde/argocd-demo.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns

    